version: '3.8'

services:
  jackett:
    image: your-repo/jackett:nonroot
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191
    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
